# Setup
title: Cognimates
email: cognimates@gmail.com
description: >-
 cognimates 
baseurl: "/"
url: "http://cognimates.me"

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-autoprefixer
include: ['_pages']

autoprefixer:
  browsers:
  - last 2 versions

# Assets
sass:
  style: :compressed

redirects: yes
